package com.projectos.backend.operations.web;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.JsonNode;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/** Typed write contract shared by the organization-scoped Operations resources. */
@JsonIgnoreProperties(ignoreUnknown = true)
public record OperationsMutationRequest(
        String id,
        String courseCode,
        String name,
        String category,
        String instructor,
        String startDate,
        String endDate,
        String location,
        @JsonAlias("sessionsCount") Integer sessions,
        Integer attendeesCount,
        BigDecimal cost,
        String status,
        String notes,
        String code,
        String title,
        String description,
        String penalties,
        String effectiveDate,
        String emailAddress,
        String displayName,
        UUID assignedEmployeeId,
        UUID departmentId,
        String mailboxType,
        @JsonAlias("storageQuotaMb") Integer quotaTotalMb,
        String forwardTo,
        List<String> aliases,
        @JsonAlias("employeeFilter") String employees,
        UUID employeeId,
        String employeeCode,
        String employeeName,
        String department,
        String contractCode,
        String contractType,
        String signDate,
        String expireDate,
        BigDecimal baseSalary,
        BigDecimal allowances,
        BigDecimal performanceBonus,
        Integer warningDaysRemaining,
        String period,
        String targetTitle,
        BigDecimal weightPercent,
        String targetMetric,
        String actualMetric,
        BigDecimal scorePercent,
        String ranking,
        String rankingLabel,
        String evaluatorName,
        String evaluationDate,
        Integer year,
        BigDecimal standardQuota,
        BigDecimal seniorityBonus,
        BigDecimal carriedOver,
        BigDecimal totalEntitled,
        BigDecimal usedDays,
        BigDecimal remainingDays,
        String slug,
        UUID leaderId,
        Integer membersCount,
        Integer displayOrder,
        Boolean isActive,
        String branchType,
        String address,
        String phone,
        String email,
        String managerName,
        Integer employeesCount,
        BigDecimal gpsLatitude,
        BigDecimal gpsLongitude,
        Integer gpsRadiusMeters,
        String resignationDate,
        String lastWorkingDate,
        String reasonType,
        String reasonDetail,
        String handoverReceiverName,
        String assetsNotes,
        JsonNode checklist,
        BigDecimal unpaidSalaryAmount,
        BigDecimal unusedLeaveDays,
        BigDecimal unusedLeaveCompensation,
        BigDecimal severancePay,
        BigDecimal totalSettlementAmount,
        String decisionNumber,
        String decisionDate
){
}
