package vn.uytinmang.projectos.attendance.web;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.*;
import java.util.*;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;
import vn.uytinmang.projectos.attendance.domain.*;
import vn.uytinmang.projectos.platform.api.ApiResponse;
import vn.uytinmang.projectos.platform.api.PageResponse;

@RestController
@RequestMapping("/api/v1/organizations/{organizationId}/attendance")
public class AttendanceController {
    private final AttendanceApplicationService service;
    public AttendanceController(AttendanceApplicationService service){this.service=service;}
    @GetMapping("/shifts") PageResponse<ShiftView> shifts(@PathVariable UUID organizationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.shifts(organizationId,page,size,actor(jwt),root(jwt));}
    @PostMapping("/shifts") @ResponseStatus(HttpStatus.CREATED) ApiResponse<ShiftView> createShift(@PathVariable UUID organizationId,@Valid @RequestBody ShiftRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.createShift(organizationId,request,actor(jwt),root(jwt)));}
    @PatchMapping("/shifts/{shiftId}") ApiResponse<ShiftView> updateShift(@PathVariable UUID organizationId,@PathVariable UUID shiftId,@Valid @RequestBody ShiftPatch request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.updateShift(organizationId,shiftId,request,actor(jwt),root(jwt)));}
    @DeleteMapping("/shifts/{shiftId}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteShift(@PathVariable UUID organizationId,@PathVariable UUID shiftId,@AuthenticationPrincipal Jwt jwt){service.deleteShift(organizationId,shiftId,actor(jwt),root(jwt));}

    @GetMapping("/schedules") PageResponse<ScheduleView> schedules(@PathVariable UUID organizationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.schedules(organizationId,page,size,actor(jwt),root(jwt));}
    @PostMapping("/schedules") @ResponseStatus(HttpStatus.CREATED) ApiResponse<ScheduleView> createSchedule(@PathVariable UUID organizationId,@Valid @RequestBody ScheduleRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.createSchedule(organizationId,request,actor(jwt),root(jwt)));}
    @PatchMapping("/schedules/{scheduleId}") ApiResponse<ScheduleView> updateSchedule(@PathVariable UUID organizationId,@PathVariable UUID scheduleId,@Valid @RequestBody SchedulePatch request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.updateSchedule(organizationId,scheduleId,request,actor(jwt),root(jwt)));}
    @DeleteMapping("/schedules/{scheduleId}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteSchedule(@PathVariable UUID organizationId,@PathVariable UUID scheduleId,@AuthenticationPrincipal Jwt jwt){service.deleteSchedule(organizationId,scheduleId,actor(jwt),root(jwt));}

    @GetMapping("/assignments") PageResponse<AssignmentView> assignments(@PathVariable UUID organizationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.assignments(organizationId,page,size,actor(jwt),root(jwt));}
    @PostMapping("/assignments") @ResponseStatus(HttpStatus.CREATED) ApiResponse<AssignmentView> createAssignment(@PathVariable UUID organizationId,@Valid @RequestBody AssignmentRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.createAssignment(organizationId,request,actor(jwt),root(jwt)));}
    @PatchMapping("/assignments/{assignmentId}") ApiResponse<AssignmentView> updateAssignment(@PathVariable UUID organizationId,@PathVariable UUID assignmentId,@Valid @RequestBody AssignmentPatch request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.updateAssignment(organizationId,assignmentId,request,actor(jwt),root(jwt)));}
    @DeleteMapping("/assignments/{assignmentId}") @ResponseStatus(HttpStatus.NO_CONTENT) void deleteAssignment(@PathVariable UUID organizationId,@PathVariable UUID assignmentId,@AuthenticationPrincipal Jwt jwt){service.deleteAssignment(organizationId,assignmentId,actor(jwt),root(jwt));}

    @PostMapping("/check-in") ApiResponse<RecordView> checkIn(@PathVariable UUID organizationId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.checkIn(organizationId,actor(jwt),root(jwt)));}
    @PostMapping("/check-out") ApiResponse<RecordView> checkOut(@PathVariable UUID organizationId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.checkOut(organizationId,actor(jwt),root(jwt)));}
    @GetMapping("/records") PageResponse<RecordView> records(@PathVariable UUID organizationId,@RequestParam(required=false)UUID employeeId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.records(organizationId,employeeId,from,to,page,size,actor(jwt),root(jwt));}
    @GetMapping("/timesheet") PageResponse<TimesheetView> timesheet(@PathVariable UUID organizationId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.timesheet(organizationId,from,to,page,size,actor(jwt),root(jwt));}

    @GetMapping("/adjustments") PageResponse<AdjustmentView> adjustments(@PathVariable UUID organizationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.adjustments(organizationId,page,size,actor(jwt),root(jwt));}
    @PostMapping("/adjustments") @ResponseStatus(HttpStatus.CREATED) ApiResponse<AdjustmentView> createAdjustment(@PathVariable UUID organizationId,@Valid @RequestBody AdjustmentRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.createAdjustment(organizationId,request,actor(jwt),root(jwt)));}
    @PostMapping("/adjustments/{adjustmentId}/decision") ApiResponse<AdjustmentView> decideAdjustment(@PathVariable UUID organizationId,@PathVariable UUID adjustmentId,@Valid @RequestBody DecisionRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.decideAdjustment(organizationId,adjustmentId,request,actor(jwt),root(jwt)));}

    @GetMapping("/leave-requests") PageResponse<LeaveView> leaves(@PathVariable UUID organizationId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.leaves(organizationId,page,size,actor(jwt),root(jwt));}
    @PostMapping("/leave-requests") @ResponseStatus(HttpStatus.CREATED) ApiResponse<LeaveView> createLeave(@PathVariable UUID organizationId,@Valid @RequestBody LeaveRequestBody request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.createLeave(organizationId,request,actor(jwt),root(jwt)));}
    @PostMapping("/leave-requests/{leaveId}/decision") ApiResponse<LeaveView> decideLeave(@PathVariable UUID organizationId,@PathVariable UUID leaveId,@Valid @RequestBody DecisionRequest request,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.decideLeave(organizationId,leaveId,request,actor(jwt),root(jwt)));}
    @PostMapping("/leave-requests/{leaveId}/cancel") ApiResponse<LeaveView> cancelLeave(@PathVariable UUID organizationId,@PathVariable UUID leaveId,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.cancelLeave(organizationId,leaveId,actor(jwt),root(jwt)));}

    @GetMapping("/reports/daily") PageResponse<TimesheetView> dailyReport(@PathVariable UUID organizationId,@RequestParam@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate date,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@AuthenticationPrincipal Jwt jwt){return service.timesheet(organizationId,date,date,page,size,actor(jwt),root(jwt));}
    @GetMapping("/reports/monthly") ApiResponse<MonthlyReport> monthlyReport(@PathVariable UUID organizationId,@RequestParam@DateTimeFormat(pattern="yyyy-MM")YearMonth month,@AuthenticationPrincipal Jwt jwt){return ApiResponse.of(service.monthlyReport(organizationId,month,actor(jwt),root(jwt)));}

    private UUID actor(Jwt jwt){return UUID.fromString(jwt.getClaimAsString("uid"));} private boolean root(Jwt jwt){return "ROOT_ADMIN".equals(jwt.getClaimAsString("role"));}
    public record ShiftRequest(@NotBlank@Size(max=150)String name,@NotNull LocalTime startTime,@NotNull LocalTime endTime,@Min(0)@Max(720)Integer breakMinutes){} public record ShiftPatch(@Size(min=1,max=150)String name,LocalTime startTime,LocalTime endTime,@Min(0)@Max(720)Integer breakMinutes,Boolean active){}
    public record ScheduleSlotRequest(@NotNull UUID shiftId,@Min(1)@Max(7)int dayOfWeek){} public record ScheduleRequest(@NotBlank@Size(max=150)String name,@NotEmpty List<@Valid ScheduleSlotRequest> slots){} public record SchedulePatch(@Size(min=1,max=150)String name,Boolean active,List<@Valid ScheduleSlotRequest> slots){}
    public record AssignmentRequest(@NotNull UUID employeeId,@NotNull UUID scheduleId,@NotNull LocalDate effectiveFrom,LocalDate effectiveTo){} public record AssignmentPatch(UUID scheduleId,LocalDate effectiveFrom,LocalDate effectiveTo){}
    public record AdjustmentRequest(@NotNull LocalDate workDate,Instant checkInAt,Instant checkOutAt,@NotBlank@Size(max=1000)String reason){} public record LeaveRequestBody(@NotNull LocalDate startDate,@NotNull LocalDate endDate,@NotBlank@Size(max=1000)String reason){} public record DecisionRequest(@NotBlank String decision,@Size(max=1000)String note){}
    public record ShiftView(UUID id,String name,LocalTime startTime,LocalTime endTime,int breakMinutes,boolean active){public static ShiftView from(Shift value){return new ShiftView(value.getId(),value.getName(),value.getStartTime(),value.getEndTime(),value.getBreakMinutes(),value.isActive());}}
    public record ScheduleView(UUID id,String name,boolean active,List<ScheduleSlotView> slots){public static ScheduleView from(WorkSchedule value,List<ScheduleSlot> slots){return new ScheduleView(value.getId(),value.getName(),value.isActive(),slots.stream().map(ScheduleSlotView::from).toList());}} public record ScheduleSlotView(UUID id,UUID shiftId,int dayOfWeek){public static ScheduleSlotView from(ScheduleSlot value){return new ScheduleSlotView(value.getId(),value.getShiftId(),value.getDayOfWeek());}}
    public record AssignmentView(UUID id,UUID employeeId,UUID scheduleId,LocalDate effectiveFrom,LocalDate effectiveTo){public static AssignmentView from(ScheduleAssignment value){return new AssignmentView(value.getId(),value.getEmployeeId(),value.getScheduleId(),value.getEffectiveFrom(),value.getEffectiveTo());}}
    public record RecordView(UUID id,UUID employeeId,UUID shiftId,LocalDate workDate,String shiftName,Instant scheduledStartAt,Instant scheduledEndAt,Instant checkInAt,Instant checkOutAt,int breakMinutes,String status){public static RecordView from(AttendanceRecord value){return new RecordView(value.getId(),value.getEmployeeId(),value.getShiftId(),value.getWorkDate(),value.getShiftName(),value.getScheduledStartAt(),value.getScheduledEndAt(),value.getCheckInAt(),value.getCheckOutAt(),value.getBreakMinutes(),value.getStatus().name().toLowerCase());}}
    public record TimesheetView(UUID recordId,LocalDate workDate,String shiftName,Instant checkInAt,Instant checkOutAt,long actualMinutes,String status){public static TimesheetView from(RecordView value){long minutes=value.checkInAt()==null||value.checkOutAt()==null?0:Math.max(0,Duration.between(value.checkInAt(),value.checkOutAt()).toMinutes()-value.breakMinutes());return new TimesheetView(value.id(),value.workDate(),value.shiftName(),value.checkInAt(),value.checkOutAt(),minutes,value.status());} public static TimesheetView from(AttendanceRecord value){return from(RecordView.from(value));}}
    public record AdjustmentView(UUID id,UUID employeeId,LocalDate workDate,Instant checkInAt,Instant checkOutAt,String reason,String status,UUID reviewerId,Instant reviewedAt,String decisionNote){public static AdjustmentView from(AttendanceAdjustment value){return new AdjustmentView(value.getId(),value.getEmployeeId(),value.getWorkDate(),value.getRequestedCheckInAt(),value.getRequestedCheckOutAt(),value.getReason(),value.getStatus().name().toLowerCase(),value.getReviewerId(),value.getReviewedAt(),value.getDecisionNote());}}
    public record LeaveView(UUID id,UUID employeeId,LocalDate startDate,LocalDate endDate,String reason,String status,UUID reviewerId,Instant reviewedAt,String decisionNote){public static LeaveView from(LeaveRequest value){return new LeaveView(value.getId(),value.getEmployeeId(),value.getStartDate(),value.getEndDate(),value.getReason(),value.getStatus().name().toLowerCase(),value.getReviewerId(),value.getReviewedAt(),value.getDecisionNote());}}
    public record MonthlyReport(String month,long recordedDays,long presentDays,long actualMinutes,List<TimesheetView> items){public static MonthlyReport from(YearMonth month,List<TimesheetView> items){return new MonthlyReport(month.toString(),items.size(),items.stream().filter(value->value.checkInAt()!=null).count(),items.stream().mapToLong(TimesheetView::actualMinutes).sum(),items);}}
}
