package vn.uytinmang.projectos.attendance.domain;

import java.time.*;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import vn.uytinmang.projectos.attendance.integration.OrganizationClient;
import vn.uytinmang.projectos.attendance.web.AttendanceController;
import vn.uytinmang.projectos.platform.api.ApiException;
import vn.uytinmang.projectos.platform.api.PageResponse;

@Service
public class AttendanceApplicationService {
    private final ShiftRepository shifts; private final WorkScheduleRepository schedules; private final ScheduleSlotRepository slots;
    private final ScheduleAssignmentRepository assignments; private final AttendanceRecordRepository records; private final AttendanceAdjustmentRepository adjustments; private final LeaveRequestRepository leaves; private final OrganizationClient organization;
    AttendanceApplicationService(ShiftRepository shifts, WorkScheduleRepository schedules, ScheduleSlotRepository slots, ScheduleAssignmentRepository assignments, AttendanceRecordRepository records, AttendanceAdjustmentRepository adjustments, LeaveRequestRepository leaves, OrganizationClient organization) { this.shifts=shifts;this.schedules=schedules;this.slots=slots;this.assignments=assignments;this.records=records;this.adjustments=adjustments;this.leaves=leaves;this.organization=organization; }

    @Transactional(readOnly=true) public PageResponse<AttendanceController.ShiftView> shifts(UUID org,int page,int size,UUID actor,boolean root){requireMember(org,actor,root);return page(shifts.findByOrganizationId(org,page(page,size)).map(AttendanceController.ShiftView::from));}
    @Transactional public AttendanceController.ShiftView createShift(UUID org,AttendanceController.ShiftRequest request,UUID actor,boolean root){requireAdmin(org,actor,root);validateShift(request.startTime(),request.endTime(),request.breakMinutes());return AttendanceController.ShiftView.from(shifts.save(new Shift(org,clean(request.name()),request.startTime(),request.endTime(),request.breakMinutes()==null?0:request.breakMinutes())));}
    @Transactional public AttendanceController.ShiftView updateShift(UUID org,UUID id,AttendanceController.ShiftPatch request,UUID actor,boolean root){requireAdmin(org,actor,root);Shift shift=shift(org,id);LocalTime start=request.startTime()==null?shift.getStartTime():request.startTime();LocalTime end=request.endTime()==null?shift.getEndTime():request.endTime();int breakMinutes=request.breakMinutes()==null?shift.getBreakMinutes():request.breakMinutes();validateShift(start,end,breakMinutes);shift.update(clean(request.name()),request.startTime(),request.endTime(),request.breakMinutes(),request.active());return AttendanceController.ShiftView.from(shift);}
    @Transactional public void deleteShift(UUID org,UUID id,UUID actor,boolean root){requireAdmin(org,actor,root);Shift shift=shift(org,id);if(slots.countByShiftId(id)>0)throw conflict("shift_in_use","Remove this shift from schedules before deleting it");shifts.delete(shift);}

    @Transactional(readOnly=true) public PageResponse<AttendanceController.ScheduleView> schedules(UUID org,int page,int size,UUID actor,boolean root){requireMember(org,actor,root);return page(schedules.findByOrganizationId(org,page(page,size)).map(this::scheduleView));}
    @Transactional public AttendanceController.ScheduleView createSchedule(UUID org,AttendanceController.ScheduleRequest request,UUID actor,boolean root){requireAdmin(org,actor,root);WorkSchedule schedule=schedules.save(new WorkSchedule(org,clean(request.name())));replaceSlots(org,schedule.getId(),request.slots());return scheduleView(schedule);}
    @Transactional public AttendanceController.ScheduleView updateSchedule(UUID org,UUID id,AttendanceController.SchedulePatch request,UUID actor,boolean root){requireAdmin(org,actor,root);WorkSchedule schedule=schedule(org,id);schedule.update(clean(request.name()),request.active());if(request.slots()!=null)replaceSlots(org,id,request.slots());return scheduleView(schedule);}
    @Transactional public void deleteSchedule(UUID org,UUID id,UUID actor,boolean root){requireAdmin(org,actor,root);WorkSchedule schedule=schedule(org,id);if(assignments.countByScheduleId(id)>0)throw conflict("schedule_in_use","Remove schedule assignments before deleting it");schedules.delete(schedule);}

    @Transactional(readOnly=true) public PageResponse<AttendanceController.AssignmentView> assignments(UUID org,int page,int size,UUID actor,boolean root){requireAdmin(org,actor,root);return page(assignments.findByOrganizationId(org,page(page,size)).map(AttendanceController.AssignmentView::from));}
    @Transactional public AttendanceController.AssignmentView createAssignment(UUID org,AttendanceController.AssignmentRequest request,UUID actor,boolean root){requireAdmin(org,actor,root);organization.employee(org,request.employeeId());schedule(org,request.scheduleId());validateAssignment(org,request.employeeId(),request.effectiveFrom(),request.effectiveTo(),null);return AttendanceController.AssignmentView.from(assignments.save(new ScheduleAssignment(org,request.employeeId(),request.scheduleId(),request.effectiveFrom(),request.effectiveTo())));}
    @Transactional public AttendanceController.AssignmentView updateAssignment(UUID org,UUID id,AttendanceController.AssignmentPatch request,UUID actor,boolean root){requireAdmin(org,actor,root);ScheduleAssignment assignment=assignment(org,id);UUID scheduleId=request.scheduleId()==null?assignment.getScheduleId():request.scheduleId();LocalDate from=request.effectiveFrom()==null?assignment.getEffectiveFrom():request.effectiveFrom();LocalDate to=request.effectiveTo()==null?assignment.getEffectiveTo():request.effectiveTo();schedule(org,scheduleId);validateAssignment(org,assignment.getEmployeeId(),from,to,id);assignment.update(request.scheduleId(),request.effectiveFrom(),request.effectiveTo());return AttendanceController.AssignmentView.from(assignment);}
    @Transactional public void deleteAssignment(UUID org,UUID id,UUID actor,boolean root){requireAdmin(org,actor,root);assignments.delete(assignment(org,id));}

    @Transactional public AttendanceController.RecordView checkIn(UUID org,UUID actor,boolean root){OrganizationClient.Employee employee=employeeFor(org,actor);OrgContext context=context(org,actor,root);LocalDate workDate=LocalDate.now(context.zone());if(records.findByEmployeeIdAndWorkDate(employee.id(),workDate).isPresent())throw conflict("already_checked_in","An attendance record already exists for this work day");ShiftTiming timing=timing(org,employee.id(),workDate,context.zone());return AttendanceController.RecordView.from(records.save(new AttendanceRecord(org,employee.id(),timing.shift(),workDate,timing.start(),timing.end(),Instant.now())));}
    @Transactional public AttendanceController.RecordView checkOut(UUID org,UUID actor,boolean root){OrganizationClient.Employee employee=employeeFor(org,actor);context(org,actor,root);AttendanceRecord record=records.findFirstByEmployeeIdAndStatusOrderByWorkDateDesc(employee.id(),AttendanceRecord.Status.OPEN).orElseThrow(()->new ApiException(HttpStatus.CONFLICT,"no_open_attendance","No open attendance record to check out"));record.checkOut(Instant.now());return AttendanceController.RecordView.from(record);}
    @Transactional(readOnly=true) public AttendanceController.AttendanceScopeView scope(UUID org,UUID actor,boolean root){if(root){context(org,actor,true);return new AttendanceController.AttendanceScopeView(null,true);}OrgContext context=context(org,actor,false);return new AttendanceController.AttendanceScopeView(employeeFor(org,actor).id(),context.admin());}
    @Transactional(readOnly=true) public PageResponse<AttendanceController.RecordView> records(UUID org,UUID employeeId,LocalDate from,LocalDate to,int page,int size,UUID actor,boolean root){OrgContext context=context(org,actor,root);UUID target=attendanceTarget(org,employeeId,actor,root,context);LocalDate start=from==null?LocalDate.now(context.zone()).withDayOfMonth(1):from;LocalDate end=to==null?LocalDate.now(context.zone()):to;if(end.isBefore(start))throw bad("invalid_date_range","to must be on or after from");return page(records.findRange(org,target,start,end,page(page,size)).map(AttendanceController.RecordView::from));}
    @Transactional(readOnly=true) public PageResponse<AttendanceController.TimesheetView> timesheet(UUID org,UUID employeeId,LocalDate from,LocalDate to,int page,int size,UUID actor,boolean root){PageResponse<AttendanceController.RecordView> result=records(org,employeeId,from,to,page,size,actor,root);return new PageResponse<>(result.data().stream().map(AttendanceController.TimesheetView::from).toList(),result.meta());}

    @Transactional(readOnly=true) public PageResponse<AttendanceController.AdjustmentView> adjustments(UUID org,int page,int size,UUID actor,boolean root){OrgContext context=context(org,actor,root);Page<AttendanceAdjustment> result=context.admin()?adjustments.findByOrganizationId(org,page(page,size)):adjustments.findByOrganizationIdAndEmployeeId(org,employeeFor(org,actor).id(),page(page,size));return page(result.map(AttendanceController.AdjustmentView::from));}
    @Transactional public AttendanceController.AdjustmentView createAdjustment(UUID org,AttendanceController.AdjustmentRequest request,UUID actor,boolean root){OrgContext context=context(org,actor,root);OrganizationClient.Employee employee=employeeFor(org,actor);validateInstants(request.checkInAt(),request.checkOutAt());if(request.workDate().isAfter(LocalDate.now(context.zone())))throw bad("invalid_work_date","Adjustment date cannot be in the future");return AttendanceController.AdjustmentView.from(adjustments.save(new AttendanceAdjustment(org,employee.id(),request.workDate(),request.checkInAt(),request.checkOutAt(),clean(request.reason()))));}
    @Transactional public AttendanceController.AdjustmentView decideAdjustment(UUID org,UUID id,AttendanceController.DecisionRequest request,UUID actor,boolean root){AttendanceAdjustment adjustment=adjustment(org,id);requireApprover(org,adjustment.getEmployeeId(),actor,root);if(adjustment.getStatus()!=AttendanceAdjustment.Status.PENDING)throw conflict("adjustment_already_decided","Adjustment has already been decided");AttendanceAdjustment.Status status=decision(request.decision(),AttendanceAdjustment.Status.APPROVED,AttendanceAdjustment.Status.REJECTED);if(status==AttendanceAdjustment.Status.APPROVED){AttendanceRecord record=records.findByEmployeeIdAndWorkDate(adjustment.getEmployeeId(),adjustment.getWorkDate()).orElseGet(()->{ZoneId zone=context(org,actor,root).zone();ShiftTiming timing=timing(org,adjustment.getEmployeeId(),adjustment.getWorkDate(),zone);return records.save(new AttendanceRecord(org,adjustment.getEmployeeId(),timing.shift(),adjustment.getWorkDate(),timing.start(),timing.end(),adjustment.getRequestedCheckInAt()));});Instant checkIn=adjustment.getRequestedCheckInAt()==null?record.getCheckInAt():adjustment.getRequestedCheckInAt();Instant checkOut=adjustment.getRequestedCheckOutAt()==null?record.getCheckOutAt():adjustment.getRequestedCheckOutAt();if(checkIn!=null&&checkOut!=null&&checkOut.isBefore(checkIn))throw bad("invalid_adjustment_time","checkOutAt must be on or after checkInAt");record.adjust(adjustment.getRequestedCheckInAt(),adjustment.getRequestedCheckOutAt());}adjustment.decide(status,actor,clean(request.note()));return AttendanceController.AdjustmentView.from(adjustment);}

    @Transactional(readOnly=true) public PageResponse<AttendanceController.LeaveView> leaves(UUID org,int page,int size,UUID actor,boolean root){OrgContext context=context(org,actor,root);Page<LeaveRequest> result=context.admin()?leaves.findByOrganizationId(org,page(page,size)):leaves.findByOrganizationIdAndEmployeeId(org,employeeFor(org,actor).id(),page(page,size));return page(result.map(AttendanceController.LeaveView::from));}
    @Transactional public AttendanceController.LeaveView createLeave(UUID org,AttendanceController.LeaveRequestBody request,UUID actor,boolean root){context(org,actor,root);OrganizationClient.Employee employee=employeeFor(org,actor);if(request.endDate().isBefore(request.startDate()))throw bad("invalid_leave_range","endDate must be on or after startDate");return AttendanceController.LeaveView.from(leaves.save(new LeaveRequest(org,employee.id(),request.startDate(),request.endDate(),clean(request.reason()))));}
    @Transactional public AttendanceController.LeaveView decideLeave(UUID org,UUID id,AttendanceController.DecisionRequest request,UUID actor,boolean root){LeaveRequest leave=leave(org,id);requireApprover(org,leave.getEmployeeId(),actor,root);if(leave.getStatus()!=LeaveRequest.Status.PENDING)throw conflict("leave_already_decided","Leave request has already been decided");leave.decide(decision(request.decision(),LeaveRequest.Status.APPROVED,LeaveRequest.Status.REJECTED),actor,clean(request.note()));return AttendanceController.LeaveView.from(leave);}
    @Transactional public AttendanceController.LeaveView cancelLeave(UUID org,UUID id,UUID actor,boolean root){LeaveRequest leave=leave(org,id);if(!root&&!leave.getEmployeeId().equals(employeeFor(org,actor).id()))throw forbidden("leave_access_denied","You can only cancel your own leave request");if(leave.getStatus()!=LeaveRequest.Status.PENDING)throw conflict("leave_not_pending","Only pending leave requests can be cancelled");leave.cancel();return AttendanceController.LeaveView.from(leave);}

    @Transactional(readOnly=true) public AttendanceController.MonthlyReport monthlyReport(UUID org,UUID employeeId,YearMonth month,UUID actor,boolean root){OrgContext context=context(org,actor,root);UUID target=attendanceTarget(org,employeeId,actor,root,context);Page<AttendanceRecord> result=records.findRange(org,target,month.atDay(1),month.atEndOfMonth(),PageRequest.of(0,1000));List<AttendanceController.TimesheetView> rows=result.getContent().stream().map(AttendanceController.TimesheetView::from).toList();return AttendanceController.MonthlyReport.from(target,month,rows);}

    private void replaceSlots(UUID org,UUID scheduleId,List<AttendanceController.ScheduleSlotRequest> request){if(request==null||request.isEmpty())throw bad("schedule_slots_required","A schedule needs at least one weekly shift");Set<Integer> days=new HashSet<>();for(var slot:request){if(slot.dayOfWeek()<1||slot.dayOfWeek()>7||!days.add(slot.dayOfWeek()))throw bad("invalid_schedule_slots","Each day can have one shift and dayOfWeek must be 1-7");if(!shift(org,slot.shiftId()).isActive())throw bad("inactive_shift","Schedule slots require an active shift");}slots.deleteByScheduleId(scheduleId);slots.flush();for(var slot:request)slots.save(new ScheduleSlot(scheduleId,slot.shiftId(),slot.dayOfWeek()));}
    private ShiftTiming timing(UUID org,UUID employeeId,LocalDate workDate,ZoneId zone){List<ScheduleAssignment> active=assignments.findActive(org,employeeId,workDate);if(active.size()!=1)throw new ApiException(HttpStatus.CONFLICT,"schedule_not_assigned","Exactly one active work schedule is required");WorkSchedule schedule=schedule(org,active.getFirst().getScheduleId());if(!schedule.isActive())throw bad("schedule_inactive","Assigned schedule is inactive");ScheduleSlot slot=slots.findByScheduleIdAndDayOfWeek(schedule.getId(),(short)workDate.getDayOfWeek().getValue()).orElseThrow(()->new ApiException(HttpStatus.CONFLICT,"no_shift_for_day","No shift is scheduled for this day"));Shift shift=shift(org,slot.getShiftId());if(!shift.isActive())throw bad("inactive_shift","Scheduled shift is inactive");ZonedDateTime start=ZonedDateTime.of(workDate,shift.getStartTime(),zone);ZonedDateTime end=ZonedDateTime.of(workDate,shift.getEndTime(),zone);if(!end.isAfter(start))end=end.plusDays(1);return new ShiftTiming(shift,start.toInstant(),end.toInstant());}
    private void validateAssignment(UUID org,UUID employeeId,LocalDate from,LocalDate to,UUID exclude){if(to!=null&&to.isBefore(from))throw bad("invalid_assignment_range","effectiveTo must be on or after effectiveFrom");if(!assignments.findOverlaps(org,employeeId,from,to,exclude).isEmpty())throw conflict("overlapping_schedule_assignment","Employee already has a schedule for this period");}
    private void requireApprover(UUID org,UUID targetEmployee,UUID actor,boolean root){OrgContext context=context(org,actor,root);if(context.admin())return;OrganizationClient.Employee requester=organization.employee(org,targetEmployee);OrganizationClient.Employee approver=employeeFor(org,actor);if(!approver.id().equals(requester.supervisorId()))throw forbidden("manager_approval_required","Only the direct manager or organization admin can approve");}
    private UUID attendanceTarget(UUID org,UUID requested,UUID actor,boolean root,OrgContext context){if(root){if(requested==null)throw bad("employee_required","Select an employee to view attendance");organization.employee(org,requested);return requested;}OrganizationClient.Employee self=employeeFor(org,actor);if(requested==null||requested.equals(self.id()))return self.id();OrganizationClient.Employee target=organization.employee(org,requested);if(context.admin()||self.id().equals(target.supervisorId()))return target.id();throw forbidden("attendance_access_denied","You can only view your own attendance or a direct report");}
    private OrgContext context(UUID org,UUID actor,boolean root){String timezone=organization.timezone(org);if(root)return new OrgContext(ZoneId.of(timezone),true);OrganizationClient.Access access=organization.access(org,actor);boolean admin="OWNER".equals(access.role())||"ADMIN".equals(access.role());return new OrgContext(ZoneId.of(access.timezone()),admin);}
    private void requireMember(UUID org,UUID actor,boolean root){context(org,actor,root);} private void requireAdmin(UUID org,UUID actor,boolean root){if(!context(org,actor,root).admin())throw forbidden("organization_admin_required","Organization admin access is required");}
    private OrganizationClient.Employee employeeFor(UUID org,UUID actor){OrganizationClient.Employee employee=organization.employeeByUser(org,actor);if(!"ACTIVE".equalsIgnoreCase(employee.status()))throw forbidden("employee_inactive","Employee is inactive");return employee;}
    private Shift shift(UUID org,UUID id){return shifts.findByIdAndOrganizationId(id,org).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"shift_not_found","Shift not found"));} private WorkSchedule schedule(UUID org,UUID id){return schedules.findByIdAndOrganizationId(id,org).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"schedule_not_found","Work schedule not found"));} private ScheduleAssignment assignment(UUID org,UUID id){return assignments.findByIdAndOrganizationId(id,org).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"assignment_not_found","Schedule assignment not found"));} private AttendanceAdjustment adjustment(UUID org,UUID id){return adjustments.findByIdAndOrganizationId(id,org).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"adjustment_not_found","Attendance adjustment not found"));} private LeaveRequest leave(UUID org,UUID id){return leaves.findByIdAndOrganizationId(id,org).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"leave_not_found","Leave request not found"));}
    private AttendanceController.ScheduleView scheduleView(WorkSchedule schedule){return AttendanceController.ScheduleView.from(schedule,slots.findByScheduleId(schedule.getId()));} private <T> PageResponse<T> page(Page<T> result){return PageResponse.of(result.getContent(),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages());} private PageRequest page(int page,int size){if(page<0||size<1||size>100)throw bad("invalid_pagination","page must be >= 0 and size must be between 1 and 100");return PageRequest.of(page,size,Sort.by("id"));}
    private void validateShift(LocalTime start,LocalTime end,Integer breakMinutes){if(start==null||end==null||start.equals(end))throw bad("invalid_shift_time","Shift start and end must be different");if(breakMinutes!=null&&(breakMinutes<0||breakMinutes>720))throw bad("invalid_break_minutes","breakMinutes must be between 0 and 720");} private void validateInstants(Instant in,Instant out){if(in==null&&out==null)throw bad("adjustment_time_required","At least one adjusted time is required");if(in!=null&&out!=null&&out.isBefore(in))throw bad("invalid_adjustment_time","checkOutAt must be on or after checkInAt");} private String clean(String value){return value==null?null:value.trim();} private <T extends Enum<T>> T decision(String value,T approved,T rejected){if("approve".equalsIgnoreCase(value)||"approved".equalsIgnoreCase(value))return approved;if("reject".equalsIgnoreCase(value)||"rejected".equalsIgnoreCase(value))return rejected;throw bad("invalid_decision","decision must be approve or reject");} private ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);} private ApiException conflict(String code,String message){return new ApiException(HttpStatus.CONFLICT,code,message);} private ApiException forbidden(String code,String message){return new ApiException(HttpStatus.FORBIDDEN,code,message);}
    private record OrgContext(ZoneId zone,boolean admin){} private record ShiftTiming(Shift shift,Instant start,Instant end){}
}
